# Generated by Django 2.2.2 on 2019-06-10 13:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.CharField(blank=True, db_column='DepartmentID', max_length=2, primary_key=True, serialize=False)),
                ('departmentname', models.CharField(blank=True, db_column='DepartmentName', max_length=22, null=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('departmentid', models.CharField(db_column='DepartmentID', max_length=2)),
                ('programid', models.CharField(db_column='ProgramID', max_length=3, primary_key=True, serialize=False)),
                ('programname', models.CharField(blank=True, db_column='ProgramName', max_length=32, null=True)),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('departmentid', models.CharField(db_column='DepartmentID', max_length=2)),
                ('roomname', models.CharField(db_column='RoomName', max_length=18, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=40, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routineid', models.DateTimeField(db_column='RoutineId', default=home.models.get_default_my_date, primary_key=True, serialize=False)),
                ('programid', models.CharField(blank=True, db_column='ProgramID', max_length=3, null=True)),
                ('teacherid', models.CharField(blank=True, db_column='TeacherID', max_length=3, null=True)),
                ('subjectid', models.CharField(blank=True, db_column='SubjectID', max_length=13, null=True)),
                ('ltp', models.CharField(blank=True, db_column='LTP', max_length=2, null=True)),
                ('period', models.IntegerField(blank=True, db_column='Period', null=True)),
                ('day', models.IntegerField(blank=True, db_column='Day', null=True)),
                ('roomname', models.CharField(blank=True, db_column='RoomName', max_length=18, null=True)),
            ],
            options={
                'db_table': 'routine',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectid', models.CharField(blank=True, db_column='SubjectID', max_length=13, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(blank=True, db_column='SubjectName', max_length=50, null=True)),
                ('departmentid', models.CharField(blank=True, db_column='DepartmentID', max_length=2, null=True)),
                ('tyear', models.CharField(blank=True, db_column='TYear', max_length=3, null=True)),
                ('tpart', models.CharField(blank=True, db_column='TPart', max_length=2, null=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.CharField(blank=True, db_column='TeacherID', max_length=3, primary_key=True, serialize=False)),
                ('teachername', models.CharField(blank=True, db_column='TeacherName', max_length=32, null=True)),
                ('departmentid', models.CharField(blank=True, db_column='DepartmentID', max_length=2, null=True)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', default='', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=5, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=32, null=True)),
                ('usertype', models.CharField(blank=True, db_column='UserType', max_length=6, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
